name 'Docker'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Docker'
long_description 'Installs/Configures Docker'
version '0.1.0'
depends 'docker', '~> 1.0'